// Type declarations for the build-time generated embeddings file.
// The implementation (chatbot-embeddings.ts) is generated by scripts/embed-knowledge.ts
// and gitignored. This stub satisfies TypeScript resolution.
import type { EmbeddedChunk } from './chatbot-rag';
export declare const embeddedChunks: EmbeddedChunk[];
