#!/usr/bin/env tsx
/**
 * Build-time script: embed all knowledge chunks via Gemini gemini-embedding-001.
 * Outputs src/lib/chatbot-embeddings.ts (gitignored, regenerated on every deploy).
 *
 * Incremental: uses a SHA-256 content hash per chunk to skip re-embedding unchanged text.
 * Run: tsx scripts/embed-knowledge.ts
 */
import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { knowledgeChunks } from '../src/lib/chatbot-knowledge.ts';

const API_KEY = process.env.GEMINI_API_KEY;
if (!API_KEY) {
  console.warn('[embed] GEMINI_API_KEY not set — writing empty embeddings, RAG will use context-stuffing fallback.');
  writeFileSync(
    join(process.cwd(), 'src/lib/chatbot-embeddings.ts'),
    [
      '// AUTO-GENERATED — GEMINI_API_KEY was not set at build time.',
      '// RAG falls back to full context stuffing. Set GEMINI_API_KEY and rebuild.',
      'import type { EmbeddedChunk } from \'./chatbot-rag\';',
      'export const embeddedChunks: EmbeddedChunk[] = [];',
      '',
    ].join('\n'),
  );
  process.exit(0);
}

const OUT_PATH = join(process.cwd(), 'src/lib/chatbot-embeddings.ts');
const CACHE_PATH = join(process.cwd(), 'src/lib/chatbot-embeddings-cache.json');

type CacheEntry = { hash: string; embedding: number[] };
type Cache = Record<string, CacheEntry>;

function sha256(text: string): string {
  return createHash('sha256').update(text).digest('hex');
}

async function embedText(text: string): Promise<number[]> {
  const url = `https://generativelanguage.googleapis.com/v1beta/models/gemini-embedding-001:embedContent?key=${API_KEY}`;
  const res = await fetch(url, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ model: 'models/gemini-embedding-001', content: { parts: [{ text }] } }),
  });
  if (!res.ok) {
    const body = await res.text();
    throw new Error(`Gemini embedding API error ${res.status}: ${body}`);
  }
  const data = await res.json() as { embedding: { values: number[] } };
  return data.embedding.values;
}

function writeEmptyEmbeddings(reason: string) {
  console.warn(`[embed] ${reason} — writing empty embeddings, RAG uses context-stuffing fallback.`);
  writeFileSync(
    OUT_PATH,
    [
      '// AUTO-GENERATED — embedding unavailable at build time.',
      '// RAG falls back to full context stuffing. See scripts/embed-knowledge.ts.',
      'import type { EmbeddedChunk } from \'./chatbot-rag\';',
      'export const embeddedChunks: EmbeddedChunk[] = [];',
      '',
    ].join('\n'),
  );
}

async function main() {
  const cache: Cache = existsSync(CACHE_PATH)
    ? JSON.parse(readFileSync(CACHE_PATH, 'utf8'))
    : {};

  const results: { id: string; embedding: number[] }[] = [];
  let embedded = 0;
  let cached = 0;

  for (const chunk of knowledgeChunks) {
    const hash = sha256(chunk.text);
    const hit = cache[chunk.id];
    if (hit && hit.hash === hash) {
      results.push({ id: chunk.id, embedding: hit.embedding });
      cached++;
      continue;
    }
    console.log(`[embed] embedding: ${chunk.id}`);
    let embedding: number[];
    try {
      embedding = await embedText(chunk.text);
    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message : String(err);
      writeEmptyEmbeddings(`embedding failed (${msg.slice(0, 120)})`);
      process.exit(0);
    }
    cache[chunk.id] = { hash, embedding };
    results.push({ id: chunk.id, embedding });
    embedded++;
  }

  // Prune stale cache entries for removed chunks
  const activeIds = new Set(knowledgeChunks.map((c) => c.id));
  for (const id of Object.keys(cache)) {
    if (!activeIds.has(id)) delete cache[id];
  }

  writeFileSync(CACHE_PATH, JSON.stringify(cache, null, 2));
  writeFileSync(
    OUT_PATH,
    [
      '// AUTO-GENERATED by scripts/embed-knowledge.ts — do not edit manually.',
      `// Generated: ${new Date().toISOString()}`,
      `// Chunks: ${results.length}`,
      'import type { EmbeddedChunk } from \'./chatbot-rag\';',
      '',
      `export const embeddedChunks: EmbeddedChunk[] = ${JSON.stringify(results, null, 2)};`,
      '',
    ].join('\n'),
  );

  console.log(`[embed] done — embedded: ${embedded}, cached: ${cached}, total: ${results.length}`);
}

main().catch((err) => {
  console.error('[embed] fatal:', err);
  process.exit(1);
});
